x-docker-common: &docker-common
  env_file: .env.staging
  image: pycon-etl
  build:
    context: .
    dockerfile: Dockerfile.test
  volumes:
    - ./sqlite:/opt/airflow/sqlite
    # you can comment out the following line if you don't have service-account.json
    - ./service-account.json:/opt/airflow/service-account.json
  restart: unless-stopped
  logging:
    driver: json-file
    options:
      max-size: 10m

services:
  airflow:
    <<: *docker-common
    container_name: airflow
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always

  scheduler:
    <<: *docker-common
    container_name: scheduler
    command: scheduler
    restart: always
    depends_on:
      - airflow
