site_name: PyCon Taiwan ETL
theme:
  name: "material"

nav:
  - Home: "README.md"
  - Guide:
    - Contributing: "CONTRIBUTING.md"
    - Maintenance: "MAINTENANCE.md"
    - Deployment: "DEPLOYMENT.md"
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
