name: Publish documentation

on:
  push:
    branches:
      - master

jobs:
  publish-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
      - name: Build docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make build-docs
      - name: Push doc to Github Page
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
