name: Python CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  AIRFLOW_TEST_MODE: true
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt -r requirements-dev.txt -c constraints-3.8.txt
          pip install black==19.10b0 click==7.1.2

      - name: Run linters
        run: make lint

      - name: Run test
        run: make test

      - name: Coverage
        run: make coverage

    # CD part
    # - name: Push dags to GCS
    #   not implemented yet
